export let keymap = {
    'a': 'c4',
    's': 'd4',
    'd': 'e4',
    'f': 'f4',
    'g': 'g4',
    'h': 'a4',
    'j': 'b4',
    'k': 'c5',
    'l': 'd5',
    ';': 'e5',
    //   '\'': 'f5', // this causes search to pop up on firefox and the note never ends, destroying your ears
    'w': 'c4s',
    'e': 'd4s',
    'r': 'c4',
    't': 'f4s',
    'y': 'g4s',
    'u': 'a4s',
    'i': 'c5s',
    'o': 'c5s',
    'p': 'd5s',
};